node {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        }
        junit 'test-reports/results.xml'
    }
    stage('Manual Approval'){
        input message: 'Apakah Anda ingin melanjutkan ke tahap berikutnya?'
        if (input == 'yes') {
            echo 'Melanjutkan ke tahap berikutnya'
        } else {
            error 'Pengguna membatalkan proses'
        }
    }
    stage('Deliver') {
        docker.image('cdrx/pyinstaller-linux:python2').inside {
            sh 'pyinstaller --onefile sources/add2vals.py'
            input message: 'Sudah selesai menggunakan React App? (Klik "Proceed" untuk mengakhiri)' 
            sh 'echo "Selesai!"'
        }
        archiveArtifacts 'dist/add2vals'
    }
}